version: '3.8'

services:
  web:
    platform: linux/x86_64
    build: .
    image: org_profit_server_prod
    stdin_open: true
    tty: true
    environment:
      - DBHOST=postgresql
      - DBUSER=postgres
      - DBPASS=root
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: org_profit_server_prod_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgresdb:/var/lib/postgresql/data/

volumes:
  postgresdb:
